### ISSUE TITLE
After upgrading the NuGet packages, there is a 'missing' type: 'KeyValuePathSegment'

### ISSUE THREAD

**Issue by alphadon-chris** [KevinDockx/ODataV4_Course#1]
Taking the Chapter 6 end project and upgrading the NuGet packages, I can resolve all of the upgrade issues except this one. How do I need to refactor or what do I need to include to get this type?

![image](https://cloud.githubusercontent.com/assets/3036288/25157222/6ecffe50-2465-11e7-8070-d40d797a5724.png)

[packages.txt](https://github.com/KevinDockx/ODataV4_Course/files/931358/packages.txt)

Thanks,
Alphadon

**Comment by KevinDockx** [comment]
It looks like the KeyValuePathSegment class was defined in System.Web.OData up to v5.9, but is no longer available in System.Web.OData v6.0, which is why you're hitting that error. The good news is that this is just a helper method that makes it easy to get the key of an OData URI (essentially it's just a bit of parsing & error checking, for which it uses the now no longer available KeyValuePathSegment). I'm going to look into how I can rewrite it, and I'll get back to you.

**Comment by alphadon-chris** [comment]
Kevin, any update on this?

**Comment by KevinDockx** [comment]
I'm currently out of the country on holiday, without a laptop.  This is first on my list when I get back :-)

**Comment by KevinDockx** [comment]
Hi, 

took some time (sorry 'bout the delay); it came down to changing two method in ODataHelpers because the classes used are no longer available after upgrading to a newer OData version.  This should solve the issue:

        public static ODataPath CreateODataPath(this HttpRequestMessage request, Uri uri)
        {
            if (uri == null)
            {
                throw new ArgumentNullException("uri");
            }

            var newRequest = new HttpRequestMessage(HttpMethod.Get, uri);
            var route = request.GetRouteData().Route;

            var newRoute = new HttpRoute(
                route.RouteTemplate,
                new HttpRouteValueDictionary(route.Defaults),
                new HttpRouteValueDictionary(route.Constraints),
                new HttpRouteValueDictionary(route.DataTokens),
                route.Handler);

            // get original configuration
            var configurationFromOriginalRequest = request.GetConfiguration();

            // set configuration on the new request object to match the
            // original configuration
            newRequest.SetConfiguration(configurationFromOriginalRequest);

            var path = configurationFromOriginalRequest.VirtualPathRoot;
            var routeData = newRoute.GetRouteData(path, newRequest);
            if (routeData == null)
            {
                throw new InvalidOperationException("This link is not a valid OData link.");
            }

            return newRequest.ODataProperties().Path;
        }

        public static TKey GetKeyValue<TKey>(this HttpRequestMessage request, Uri uri)
        {
            if (uri == null)
            {
                throw new ArgumentNullException("uri");
            }

            //get the odata path Ex: ~/entityset/key/$links/navigation
            var odataPath = request.CreateODataPath(uri);
            var segments = odataPath.Segments;

           var keySegment = odataPath.Segments
                .OfType<Microsoft.OData.UriParser.KeySegment>().LastOrDefault();

            if (keySegment == null || !keySegment.Keys.Any())
            {
                throw new InvalidOperationException("This link does not contain a key.");
            }

            // found a key segment.  Return the key value of the last segment
            return (TKey)keySegment.Keys.Last().Value;              
        }
